[build]
  functions = "netlify/functions"

[functions."trpc"]
  included_files = ["netlify/functions/data/**"]

[[redirects]]
  from = "/api/trpc/*"
  to = "/.netlify/functions/trpc"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
