#!/usr/bin/env bash
# ============================================================
# update_and_deploy.sh
# 新しいTrackman CSVを追加して自動ビルド・デプロイするスクリプト
#
# 使い方:
#   ./update_and_deploy.sh /path/to/2026_data.csv
#
# 処理内容:
#   1. 新CSVをマスターデータにマージ
#   2. 全JSONデータを再計算（リーダーボード、個人詳細、ゾーンデータ）
#   3. フロントエンドをビルド
#   4. GitHubにプッシュ（自動デプロイ）
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON_SCRIPT="/home/analyst18/tokyo-baseball/update_season.py"
ROKUDAI_DIR="/home/analyst18/rokudai_statcast"

# ============================================================
# 引数チェック
# ============================================================
if [ -z "$1" ]; then
    echo "使い方: $0 /path/to/new_data.csv"
    echo ""
    echo "例: $0 /home/analyst18/2026_spring.csv"
    exit 1
fi

CSV_PATH="$1"

if [ ! -f "$CSV_PATH" ]; then
    echo "エラー: ファイルが見つかりません: $CSV_PATH"
    exit 1
fi

echo "=============================================="
echo " ROKUDAI STATCAST データ更新"
echo "=============================================="
echo " CSV: $CSV_PATH"
echo " 開始時刻: $(date)"
echo "=============================================="

# ============================================================
# Step 1: Pythonスクリプトでデータ処理
# ============================================================
echo ""
echo "[1/4] データ処理中..."
python3 "$PYTHON_SCRIPT" "$CSV_PATH"
echo "データ処理完了"

# ============================================================
# Step 2: フロントエンドビルド
# ============================================================
echo ""
echo "[2/4] フロントエンドビルド中..."
cd "$ROKUDAI_DIR"
BUILD_TARGET=ghpages npx vite build 2>&1 | tail -10

# Find the new JS bundle filename
NEW_JS=$(ls "$ROKUDAI_DIR/dist/public/assets/index-"*.js 2>/dev/null | head -1)
NEW_CSS=$(ls "$ROKUDAI_DIR/dist/public/assets/index-"*.css 2>/dev/null | head -1)

if [ -z "$NEW_JS" ]; then
    echo "エラー: ビルド成果物が見つかりません"
    exit 1
fi

JS_FILENAME=$(basename "$NEW_JS")
CSS_FILENAME=$(basename "$NEW_CSS")
echo "新しいJSバンドル: $JS_FILENAME"

# ============================================================
# Step 3: アセットをコピー・index.html更新
# ============================================================
echo ""
echo "[3/4] アセット更新中..."
cp "$NEW_JS" "$SCRIPT_DIR/assets/"
cp "$NEW_CSS" "$SCRIPT_DIR/assets/"

# Update index.html JS/CSS reference (match full path including /-statscast/ prefix)
cd "$SCRIPT_DIR"
sed -i "s|/-statscast/assets/index-[A-Za-z0-9_-]*\.js|/-statscast/assets/$JS_FILENAME|g" index.html
sed -i "s|/-statscast/assets/index-[A-Za-z0-9_-]*\.css|/-statscast/assets/$CSS_FILENAME|g" index.html
echo "index.html 更新完了 (JS: $JS_FILENAME, CSS: $CSS_FILENAME)"

# ============================================================
# Step 4: Gitコミット・プッシュ
# ============================================================
echo ""
echo "[4/4] GitHubへプッシュ中..."
cd "$SCRIPT_DIR"
git add -A

# Check if there are changes to commit
if git diff --staged --quiet; then
    echo "変更なし。コミットをスキップします。"
else
    YEAR=$(python3 -c "
import pandas as pd
df = pd.read_csv('$CSV_PATH', nrows=100, low_memory=False)
for col in ['UTCDate', 'Date']:
    if col in df.columns:
        parsed = pd.to_datetime(df[col], errors='coerce')
        year = parsed.dt.year.dropna()
        if len(year) > 0:
            print(int(year.mode()[0]))
            exit()
print('unknown')
" 2>/dev/null || echo "unknown")

    git commit -m "$(cat <<EOF
Add $YEAR season data from $(basename $CSV_PATH)

- Updated all yearData JSONs with $YEAR season statistics
- Regenerated player detail files (batting, pitching, impact zones)
- Auto-generated by update_and_deploy.sh

Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>
EOF
)"
    git push origin main
    echo ""
    echo "=============================================="
    echo " デプロイ完了!"
    echo " URL: https://ryoheisaitoanalyst18-design.github.io/-statscast/"
    echo " ※ GitHub Actions が完了するまで1〜2分かかります"
    echo "=============================================="
fi

echo ""
echo "完了時刻: $(date)"
